"""Dodano model Assessment

Revision ID: 51b6f3b5d0fa
Revises: d664af4c6d23
Create Date: 2024-10-10 15:09:32.148273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b6f3b5d0fa'
down_revision = 'd664af4c6d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('kolokwium1', sa.Float(), nullable=True),
    sa.Column('kolokwium2', sa.Float(), nullable=True),
    sa.Column('projekt', sa.Float(), nullable=True),
    sa.Column('aktywnosc', sa.Float(), nullable=True),
    sa.Column('inne', sa.Float(), nullable=True),
    sa.Column('uwagi', sa.Text(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.FLOAT(), nullable=True))

    op.drop_table('assessments')
    # ### end Alembic commands ###
